import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Use the default sidebar generated from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
